# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15payment_service.proto\x12\x07payment\"Q\n\x15ProcessPaymentRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12\x16\n\x0epayment_method\x18\x03 \x01(\t\"-\n\x17GetPaymentStatusRequest\x12\x12\n\npayment_id\x18\x01 \x01(\t\"5\n\x0fPaymentResponse\x12\x12\n\npayment_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2\xac\x01\n\x0ePaymentService\x12J\n\x0eProcessPayment\x12\x1e.payment.ProcessPaymentRequest\x1a\x18.payment.PaymentResponse\x12N\n\x10GetPaymentStatus\x12 .payment.GetPaymentStatusRequest\x1a\x18.payment.PaymentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_PROCESSPAYMENTREQUEST']._serialized_start=34
  _globals['_PROCESSPAYMENTREQUEST']._serialized_end=115
  _globals['_GETPAYMENTSTATUSREQUEST']._serialized_start=117
  _globals['_GETPAYMENTSTATUSREQUEST']._serialized_end=162
  _globals['_PAYMENTRESPONSE']._serialized_start=164
  _globals['_PAYMENTRESPONSE']._serialized_end=217
  _globals['_PAYMENTSERVICE']._serialized_start=220
  _globals['_PAYMENTSERVICE']._serialized_end=392
# @@protoc_insertion_point(module_scope)
