version: '3.8'
services:
  user_service:
    build:
      context: ./user_service
    ports:
      - "5001:5001"
  order_service:
    build:
      context: ./order_service
    ports:
      - "5002:5002"
  payment_service:
    build:
      context: ./payment_service
    ports:
      - "5003:5003"
  tracking_service:
    build:
      context: ./tracking_service
    ports:
      - "5004:5004"
  review_service:
    build:
      context: ./review_service
    ports:
      - "5005:5005"
