# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tracking_service_pb2 as tracking__service__pb2


class TrackingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TrackOrder = channel.unary_unary(
                '/tracking.TrackingService/TrackOrder',
                request_serializer=tracking__service__pb2.TrackOrderRequest.SerializeToString,
                response_deserializer=tracking__service__pb2.TrackingResponse.FromString,
                )
        self.GetTrackingDetails = channel.unary_unary(
                '/tracking.TrackingService/GetTrackingDetails',
                request_serializer=tracking__service__pb2.GetTrackingDetailsRequest.SerializeToString,
                response_deserializer=tracking__service__pb2.TrackingResponse.FromString,
                )


class TrackingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TrackOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrackingDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrackingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TrackOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.TrackOrder,
                    request_deserializer=tracking__service__pb2.TrackOrderRequest.FromString,
                    response_serializer=tracking__service__pb2.TrackingResponse.SerializeToString,
            ),
            'GetTrackingDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrackingDetails,
                    request_deserializer=tracking__service__pb2.GetTrackingDetailsRequest.FromString,
                    response_serializer=tracking__service__pb2.TrackingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tracking.TrackingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TrackingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TrackOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tracking.TrackingService/TrackOrder',
            tracking__service__pb2.TrackOrderRequest.SerializeToString,
            tracking__service__pb2.TrackingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTrackingDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tracking.TrackingService/GetTrackingDetails',
            tracking__service__pb2.GetTrackingDetailsRequest.SerializeToString,
            tracking__service__pb2.TrackingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
