# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: review_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14review_service.proto\x12\x06review\"\\\n\x10\x41\x64\x64ReviewRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x13\n\x0breview_text\x18\x03 \x01(\t\x12\x0e\n\x06rating\x18\x04 \x01(\x05\"\'\n\x11GetReviewsRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\"3\n\x0eReviewResponse\x12\x11\n\treview_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"2\n\x0fReviewsResponse\x12\x1f\n\x07reviews\x18\x01 \x03(\x0b\x32\x0e.review.Review\"Q\n\x06Review\x12\x11\n\treview_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x13\n\x0breview_text\x18\x03 \x01(\t\x12\x0e\n\x06rating\x18\x04 \x01(\x05\x32\x90\x01\n\rReviewService\x12=\n\tAddReview\x12\x18.review.AddReviewRequest\x1a\x16.review.ReviewResponse\x12@\n\nGetReviews\x12\x19.review.GetReviewsRequest\x1a\x17.review.ReviewsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'review_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ADDREVIEWREQUEST']._serialized_start=32
  _globals['_ADDREVIEWREQUEST']._serialized_end=124
  _globals['_GETREVIEWSREQUEST']._serialized_start=126
  _globals['_GETREVIEWSREQUEST']._serialized_end=165
  _globals['_REVIEWRESPONSE']._serialized_start=167
  _globals['_REVIEWRESPONSE']._serialized_end=218
  _globals['_REVIEWSRESPONSE']._serialized_start=220
  _globals['_REVIEWSRESPONSE']._serialized_end=270
  _globals['_REVIEW']._serialized_start=272
  _globals['_REVIEW']._serialized_end=353
  _globals['_REVIEWSERVICE']._serialized_start=356
  _globals['_REVIEWSERVICE']._serialized_end=500
# @@protoc_insertion_point(module_scope)
